name: Create GetScreen Windows Machine

on:
  workflow_dispatch:
  
jobs:
  create_machine:
    runs-on: ubuntu-latest
    steps:
      - name: Create GetScreen Windows Machine
        run: |
          curl -X POST \
            -H "Authorization: Bearer elctXfgXeIFCFqha3MKSBuGXf1W1mFnHhsanlRNSKhN3ojlARaekiI5b1EzDgFwLjx6WoEPWr6jdFajRmZuzwhZKtShDJyPcrdHReirnh3ixbBtGCIsNnaNRKUnDGwh1" \
            -d "image=windows" \
            -d "duration=4" \
            https://getscreen.me/api/v1/machines
