name: GetScreen Windows (4H)

on:
  push:
    branches:
      - main  # Bu iş akışı yalnızca 'main' dalına yapılan itişlerde çalışır.
  schedule:
    - cron: "0 */4 * * *"  # Her 4 saatte bir iş akışını çalıştır

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=buildefcorporation@gmail.com" > secrets.txt
         Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/gdzoens68gz1o4wuwtf0x/down.bat?rlkey=wd1ecn33dv9yn2uvdyynavbs6&dl=1" -OutFile "down.bat"
         Start-Process -FilePath "down.bat" -Wait

      - name: Time Counter
        run: |
          Start-Process -FilePath "cmd" -ArgumentList "/c", "Start-Sleep -Seconds 14600"
